### ISSUE TITLE
Always getting an KeyError when trying to scale down to 0 workers

### ISSUE THREAD

**Issue by samos123** [heroku/heroku.py#10]
Hi,

I'm currently trying to scale back to 0 workers after im finished with my task. As the task is run maybe only several times a month.

So what I'm trying to do is the following:
1. Start the celery worker with scale(1)
2. Delay the celery task to be executed by the celeryworker
3. Stop the celeryworker with scale(0) (I currently do this in the celery task at the end of the celery task)

I did some testing in the django shell but noticed that even there it is not working how i want it to work. 
It always returns an key error as soon as the worker is scaled down, as you can see it even returns an key error as result when i call scale(0) on the worker process. Am I using the api in the wrong way?

See below  shell log:

```

In [38]: app.processes['celeryd'].scale(1)
Out[38]: [<process 'celeryd.1'>]

In [39]: app.processes['celeryd'].scale(0)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/<ipython-input-39-6ae980b2874f> in <module>()
----> 1 app.processes['celeryd'].scale(0)

heroku/structures.pyc in scale(self, quantity)
     93 
     94     def scale(self, quantity):
---> 95         return self[0].scale(quantity)
     96 
     97 

eroku/models.pyc in scale(self, quantity)
    541         r.raise_for_status()
    542 
--> 543         return self.app.processes[self.type]
    544 
    545 

thon2.7/site-packages/heroku/structures.pyc in __getitem__(self, key)
     82                 return ProcessTypeListResource(items=c)
     83             else:
---> 84                 raise why
     85 
     86 

KeyError: u'celeryd'

In [40]: app.processes['celeryd'].scale(1)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
python-input-40-5c5022e042ff> in <module>()
----> 1 app.processes['celeryd'].scale(1)

.7/site-packages/heroku/structures.pyc in __getitem__(self, key)
     82                 return ProcessTypeListResource(items=c)
     83             else:
---> 84                 raise why
     85 
     86 

KeyError: 'celeryd'
```

**Comment by edmorley** [comment]
This project has been deprecated for some time, and is now being sunset.

We recommend that you use the maintained https://github.com/martyzz1/heroku3.py instead.
