### ISSUE TITLE
unexpected keyword argument 'session'

### ISSUE THREAD

**Issue by kr** [heroku/heroku.py#18]
The readme says:

```
cloud = Heroku(session=session)
```

When I try this, I get:

```
Traceback (most recent call last):
  File "./merge", line 18, in <module>
    cloud = Heroku(session=session)
TypeError: __init__() got an unexpected keyword argument 'session'
```

**Comment by edmorley** [comment]
This project has been deprecated for some time, and is now being sunset.

We recommend that you use the maintained https://github.com/martyzz1/heroku3.py instead.
