### ISSUE TITLE
Logs with tail=True hangs after about 100 entries

### ISSUE THREAD

**Issue by jtushman** [heroku/heroku.py#27]
with the following requirements.txt:

```
requests==0.14.2
git+git://github.com/heroku/heroku.py.git
```

(note had to peg `requests` to get `r = requests.get(r.content, verify=False, prefetch=False)` to work)

and the following snipit:

```
 for line in self.app.logs(tail=True):
 print line
```

the script will print about 100 lines, then hang.

Any ideas on what I am doing wrong?

Thanks!

**Comment by edmorley** [comment]
This project has been deprecated for some time, and is now being sunset.

We recommend that you use the maintained https://github.com/martyzz1/heroku3.py instead.
