### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by KristianOellegaard** [heroku/heroku.py#28]
Hi there,

Isn't it about time for a new release? There are a few fixes in there more than 8 months old, that everyone would benefit from. I believe #16 and #11 are closed using the latest checkout on master.

Kind regards,

Kristian

**Comment by gueyeb** [comment]
@kennethreitz ping ?

**Comment by edmorley** [comment]
This project has been deprecated for some time, and is now being sunset.

We recommend that you use the maintained https://github.com/martyzz1/heroku3.py instead.
