### ISSUE TITLE
Process types with 0 running instances cause KeyError

### ISSUE THREAD

**Issue by bengl3rt** [heroku/heroku.py#4]
Say I have a pretty standard procfile declaring a "web" and a "worker" process. The default state for my app is to have a single web dyno running, and no workers running, using heroku.py to file up workers on demand. 

However, when 0 workers are running, 

app.processes['worker'].scale(0)

causes KeyError. In other words the process map only contains information about currently running dynos regardless of the contents of the procfile, making it impossible to automate the transition from 0 to 1 workers.

**Comment by edmorley** [comment]
This project has been deprecated for some time, and is now being sunset.

We recommend that you use the maintained https://github.com/martyzz1/heroku3.py instead.
