### ISSUE TITLE
Support scaling processes 0 to n

### ISSUE THREAD

**Issue by clee704** [heroku/heroku.py#45]
#14 made it possible to scale processes from 0 to any quantity, but #29 removed this feature. Currently, we can do this by the following hack (assuming there is no worker process running for _myapp_):

```
import heroku
from heroku.models import Process
h = heroku.from_key(...)
app = h.apps['myapp']
Process.new_from_dict({'process': 'worker'}, h, app=app).scale(10)
```

But it would be best to be supported officially.

**Comment by BenLiyanage** [comment]
FWIW this hack totally works for me.

**Comment by NicolaeNMV** [comment]
Thanks for posting the work around !

**Comment by edmorley** [comment]
This project has been deprecated for some time, and is now being sunset.

We recommend that you use the maintained https://github.com/martyzz1/heroku3.py instead.
