### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by hwkns** [heroku/heroku.py#50]
Does this library officially support Python 3?

If so, it would be nice to designate that on PyPI using classifiers in setup.py (I see that 3.0 and 3.1 are commented out in github, and PyPI lists 3.1 and 3.2, which is confusing...).

If not, what does the path forward look like?

**Comment by edmorley** [comment]
This project has been deprecated for some time, and is now being sunset.

We recommend that you use the maintained https://github.com/martyzz1/heroku3.py instead.
