### ISSUE TITLE
Why it was discontinued?

### ISSUE THREAD

**Issue by fbidu** [heroku/heroku.py#58]
Heroku is such a nice platform and having a Python wrapper around its API just makes it more awesome...

Anyways, I forked this project a few days ago and I'm trying to update it a bit... If anyone's interested: https://github.com/fbidu/pyheroku/tree/dev/

**Comment by kennethreitz** [comment]
v3 of the API is out now, and the API surface is *much* larger. There are third-party libraries that make interacting with it very easy, for example, [coreapi](http://www.coreapi.org/tools-and-resources/example-services/)
