### ISSUE TITLE
cloud.apps do not work because the url https://api.heroku.com/apps is deprecated

### ISSUE THREAD

**Issue by CarlosNeves** [heroku/heroku.py#60]
cloud.apps do not work because the url https://api.heroku.com/apps is deprecated since yesterday. Instead show the exception: "requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://api.heroku.com/apps"

Is possible to have a resolution for this issue?

Thank you.
---
Possible reason of the issue occurrence:
https://devcenter.heroku.com/changelog-items/1147
“Legacy Platform API Brownouts start May 24th
(...) final shutdown Monday, June 26th.
Please see our original deprecation announcement for further details and our status site for upcoming brownout dates and times.”

**Comment by kennethreitz** [comment]
this entire library is deprecated.

**Comment by CarlosNeves** [comment]
Workaround: https://pypi.python.org/pypi/heroku3/3.3.0
